### ISSUE TITLE
Evaluate support for JSON templates

### ISSUE THREAD

**Issue by bw-intuit** [intuit/cfn_lambda_extractor#1]
This is likely best achieved by converting to YAML prior to extraction.  The nature of how the file is processed makes JSON parsing impossible.

https://github.com/awslabs/aws-cfn-template-flip

**Comment by abhishekmangla** [comment]
I believe the above package can help to support JSON templates. Simply:

`some_yaml = to_yaml(some_json)`

I'll make this change along with some error handling and add unit tests.

**Comment by bw-intuit** [comment]
@abhishekmangla Hi Abhishek, I thought about that, the only concern is all the pseudo parameters and references Cloud Formation uses:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html

I'm not sure a straight yaml -> json conversation will work for many use cases.  Please test and let me know what you find.

**Comment by bw-intuit** [comment]
Resolved via #3 Thanks @abhishekmangla
